package org.usfirst.frc7108.Robot.subsystems;

import org.usfirst.frc7108.Robot.RobotMap;

import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;

public class Grabber extends Subsystem {
	 private final SpeedController grabberMotor1 = RobotMap.grabberKutuMotor1;
	 private final SpeedController grabberMotor2 = RobotMap.grabberKutuMotor2;
	
	 public void initDefaultCommand() {
	        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


	        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

	        // Set the default command for a subsystem here.
	        // setDefaultCommand(new MySpecialCommand());
	    }

		public void birak(double wheelSpeed) {
			grabberMotor1.set(wheelSpeed);
			grabberMotor2.set(-wheelSpeed);
		}

		public void al(double wheelSpeed) {
			grabberMotor1.set(-wheelSpeed);
			grabberMotor2.set(wheelSpeed);
		}
		
		public void kutuDur() 
		{
			grabberMotor1.set(0);
			grabberMotor2.set(0);
		}
		
	    public void periodic() {
	        // Put code here to be run every loop

	    }


}
