package org.usfirst.frc7108.Robot.commands;

import org.usfirst.frc7108.Robot.Robot;
import org.usfirst.frc7108.Robot.subsystems.Grabber;

import edu.wpi.first.wpilibj.command.Command;

public class BoxReleaseTeleop extends Command{
	
	
	 public BoxReleaseTeleop() {
		 
		 //this.seconds = _seconds;		
		    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		        requires(Robot.grabber);

		    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		    }

			// Called just before this Command runs the first time
		    protected void initialize() {
		    	//startTime = System.currentTimeMillis();
		    }

		    // Called repeatedly when this Command is scheduled to run
		    protected void execute() {
		    Robot.grabber.birak(0.8); // may need to call getJoystick() method
		    }

		    // Make this return true when this Command no longer needs to run execute()
		    protected boolean isFinished() {
		         return false;
		    }

		    // Called once after isFinished returns true
		    protected void end() 
		    {
		    	Robot.grabber.kutuDur();
		    }

		    // Called when another command which requires one or more of the same
		    // subsystems is scheduled to run
		    protected void interrupted() {
		    	end();
		    }


}
